[jupiter.logger.default]
    debug = false  # 是否在命令行输出
    enableConsole = false # 是否按命令行格式输出
    name = "default.json" #日志名称
    dir = "."  # 日志路径
[jupiter.logger.jupiter]
    debug = false  # 是否在命令行输出
    enableConsole = false # 是否按命令行格式输出
    name = "system.json" #日志名称
    dir = "."  # 日志路径
