// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package e2e

import (
	"uuid/internal/app/uuidserver/service"
	"uuid/internal/pkg/redis"
)

// Injectors from wire.go:

func CreateUuidService(redisCli redis.RedisInterface) *service.Uuid {
	options := service.Options{
		Redis: redisCli,
	}
	uuid := service.NewUuidService(options)
	return uuid
}
