[jupiter.redis.myredis.stub]
    addr = "127.0.0.1:6379"
[jupiter.redis.myredis.cluster]
    addrs =["127.0.0.1:7000","127.0.0.1:7001","127.0.0.1:7002"]
[jupiter.redis.myredistub]
    addrs = ["127.0.0.1:6379"]
[jupiter.redis.myredistub2]
    addrs = ["127.0.0.1:6379","127.0.0.1:6380","127.0.0.1:6381"]
    mode = "stub"
[jupiter.redis.myrediscluster]
    addrs =["127.0.0.1:7000","127.0.0.1:7001","127.0.0.1:7002"]
[jupiter.redis.myrediscluster2]
    addrs = ["127.0.0.1:6379"]
    mode = "cluster"

