basePath: /v1
definitions:
  main.Response:
    properties:
      code:
        type: integer
      data:
        type: object
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /user/{id}:
    get:
      consumes:
      - application/json
      description: get user by ID
      parameters:
      - description: user ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/main.Response'
        "400":
          description: failure
          schema:
            $ref: '#/definitions/main.Response'
      summary: get user by ID
swagger: "2.0"
