[jupiter.grpc.etcdserver]
    address = "etcd:///main"
    balancerName = "round_robin" # 默认值
    block = false                # 默认值
    dialTimeout = "0s"           # 默认值

[jupiter.registry.default]
    endpoints = ["localhost:2379"]
    secure = false
