[jupiter.sentinel]
    enable = true
    datasource = "files"
    [[jupiter.sentinel.flowRules]]
        resource = "some-test"
        metricType = 1         # flow.QPS
        count = 10
        controlBehavior = 0    # flow.Reject
